### ISSUE TITLE
请教一个关于域名账号权限的问题

### ISSUE THREAD

**Issue by sunjianan9900** [VinerFiner/start-acme#1]
域名在A账号下，但是函数在B账号下，提供A账号的Key和Secret执行，这样可以吗？

实际情况是：
如果我的域名在阿里云A账号下
但是我的函数都在阿里云B账号下，包括本函数

我现在部署了这个自动申请证书的函数，环境变量填写的KEY和SECRET都是A账号的

然后执行：
{
    "region": "cn-hangzhou",
    "domain": "api.xxxx.com",
    "function": "flask-countlang"
}

flask-countlang 是B账号下一个需要设置域名的函数名

结果错误是：
"errorMessage": "Error: AccessDenied code: 403, the caller is not authorized to perform 'fc:UpdateCustomDomain' on resource 'acs:fc:cn-hangzhou:B账号ID:custom-domains/api.xxxx.com' with condition '[fc:EnableCustomDomainHTTP=false]' request id: 1-3c Response: {'RequestId': '1-3c', 'Code': 'AccessDenied', 'Message': \"the caller is not authorized to perform 'fc:UpdateCustomDomain' on resource 'acs:fc:cn-hangzhou:B账号ID:custom-domains/api.xxxx.com' with condition '[fc:EnableCustomDomainHTTP=false]'\", 'statusCode': 403} is not a str",

似乎是没有更新B账号自定义域名的权限？但是函数已经提供全部权限了
<img width="738" alt="image" src="https://github.com/user-attachments/assets/e01b0b4d-12e8-40b2-9076-5984687b170e">

**Comment by VineFiner** [comment]
需要DNS的权限
AliyunDNSFullAccess
